### ISSUE TITLE
Zotero 如何添加文章检索引擎

### ISSUE THREAD

**Issue by heytxz** [heytxz/blog#4]
> 本文发布在少数派，请至少数派查看 [最新版本](https://sspai.com/post/40458)。

Zotero 是优秀的免费开源个人知识管理工具，一般用于管理学术文献，其以跨 macOS、Windows、Linux 三大平台、强大易用的功能闻名于学术圈。关于 Zotero 的使用教程数不胜数，如果你是新生或者还未使用文献管理工具，如果你需要知识管理工具，Zotero 可能是你最好的选择之一。

> 添加列表中没有的检索引擎，请在浏览器中访问检索引擎网页，并从 Zotero 的“定位”菜单中，选择“添加”。

2014 年开始使用 Zotero，曾长期为一个问题困扰：依据提示无法添加文章（文献）检索引擎。起初我以为不能是独立版，后来发现 Firefox 版也无法添加。曾于知乎提问 [如何添加文献（文章）检索引擎](https://www.zhihu.com/question/46484469) 但无人回答，逛 Zotero 官方论坛、也看了许多官方文档也都未发现解决方案…… 后经研究解决了这个问题。原本将解决方案放在独立博客与简书上，但近期我删除了简书帐号，独立博客也进行了改版并删除了所有文章。今天又有人问我，我决定再次整理解决方案，并发布于我最喜爱的少数派……

![先放一张效果图](https://user-images.githubusercontent.com/9845703/29320745-d09bd03e-820a-11e7-99aa-a03a95efdafd.png)

## 添加教程
从 Zotero `首选项` -> `高级` -> `文件和文件夹` 打开数据库文件 ，再打开控制检索引擎的 `locate/engines.json` 文件。如下图所示，`CrossRef Lookup`、`Google Scholar Search`、`Pubget Lookup` 是默认的三个检索引擎。那么如何添加新的检索引擎，比如知网？

![三个默认检索引擎](https://user-images.githubusercontent.com/9845703/29320813-f9ca86da-820a-11e7-8a50-a4134fdb3bb5.png)

### 以添加知网检索引擎为例
可以看到，上图中三对 `{}` 括号中的代码代表着三个默认的检索引擎。添加其他检索引擎只需添加类似代码。下文所示代码是知网引擎，在指定位置添加半角逗号以后，将代码复制到自己的 `engines.json` 文件中保存即可。重新打开 Zotero 即可发现知网检索引擎已被添加。

```
		"_iconSourceURI": "http://pubget.com/favicon.ico"
	},   此处要加英文（半角）逗号，然后从下面开始复制并添加文末位置
	{
		"name": "CNKI Search",
		"alias": "CNKI",
		"icon": null,
		"_urlTemplate": "http://search.cnki.net/kns/brief/Default_Result.aspx?code=SCDB&kw={z:title}",
		"description": "CNKI",
		"hidden": true,
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "http://static.wanfangdata.com.cn/wfks/img/logo_new.png"
	}
```

对于 IP 用户，可直接添加知网、万方、维普等检索引擎，就可以无忧无虑地下载文献。但对于使用学校代理的用户，需要更改 `_urlTemplate`。添加其他检索引擎事实上也只需重点修改 `_urlTemplate` 中的搜索网址。

### 如何确定搜索网址
那么如何确定 `_urlTemplate` 中的搜索网址？以万方为例：假设我们在万方搜索 `唐小筑`，网址是这样的形式 `http://s.wanfangdata.com.cn/Paper.aspx?q=唐小筑&f=top`，注意到其中 `唐小筑` 即为我们的搜索目标， 而参数 `{z:title}` 代表着 Zotero 中条目名称，那么 `_urlTemplate` 中的搜索网址就应该是：

```
http://s.wanfangdata.com.cn/Paper.aspx?q={z:title}&f=top
``` 
## 总结
Zotero 是开源应用，每一个功能对应的文件都可自行修改，但大部分人应该跟我一样，几乎不懂编程，但也不要对此恐惧。遇到问题也不妨试着找找这个问题对应功能的控制文件，无论是模仿修改还是向其他人求教都会有所帮助。

若对 Zotero 的使用有疑问欢迎讨论……

**Comment by heytxz** [comment]
1. 在 Zotero `首选项` `高级` `文件和文件夹` 点击 `打开数据文件夹`，发现了 `zotero` 文件夹；
2. 进入 `zotero` 文件夹，再进入 `locate` 文件夹，双击打开 `engines.json` 文件，会发现三段代码，它们的 `name` 分别是 `CrossRef Lookup`、`Google Scholar Search`、`Pubget Lookup`；
3. 注意 `engines.json` 文件的倒数第二行是 `}`，最后一行是 `]`。我们在 `}` 后面加个半角逗号（发现前面两段代码最后都有逗号了么），然后将前文的知网引擎代码复制在 `},`、`]` 之间，我们就有四段代码了；
4. 检查代码。四段段代码的第一行和最后一行都是 `{`、`}`，只有前三个 `]` 后面都有半角逗号，整个文件的第一行是 `[`，最后一行是 `]`，没问题的话就保存  `engines.json` 文件；
5. 重新打开 Zotero 就会发现 `CNKI` 检索引擎。如果没有的话……就在评论区说明情况吧。

**Comment by chempeng** [comment]
博客大改版了啊。最近把 zoetro 更新了，zotfile 插件反而不能用了，好尴尬。Win 环境。

**Comment by heytxz** [comment]
更新 ZotFile 插件，最新版支持的。折腾各种各样的博客引擎折腾够了，还是用最简单的 Issues 省心 :)

2017年9月6日 +0800 19:50 chempeng <notifications@github.com>，写道：
