### ISSUE TITLE
为何 Office for Mac 字体总变为 M S 明朝

### ISSUE THREAD

**Issue by heytxz** [heytxz/blog#45]
将 Office 更新至最新版本即可。如果检查更新无法检查到 Office 更新资源，比如我的就是，可到官网下载手动安装。目前我更新到 170919 版本，变字体的问题已消除：
1. 自动变 M S 明朝，如网页复制；
2. 无法将 M S 明朝字体更改为宋体等字体；
3. 检查不到 Office 更新资源的问题也消除了。

Office for macOS 确实不如 for Windows，如果需要常用 Office 不建议购买 Mac 系列，或者购买 Mac 系列的同时也购买 Parallel Desktop 来装 Windows 虚拟机。

**Comment by Leo20150407** [comment]
非常感谢 M S 明朝快烦死了

**Comment by heytxz** [comment]
当初我也是烦死了。Office for macOS 预览版更新很频繁，再遇到问题的话设置以快的频率接收预览版，更新 Office
也许就解决了。要是无法检查到更新，就去官网下载。
