### ISSUE TITLE
好用的代理服务

### ISSUE THREAD

**Issue by heytxz** [heytxz/blog#53]
此代理服务原名为 BlueCloud，我已经使用了三年，有次和客服十数次邮件来往只为帮我解决 IPV6 问题。简而言之，优势在于：高性价比 & 高稳定性 & 客服态度认真负责。

如果购入个人提供的相关服务时，建议多检索其负面信息，我曾购买私人提供的服务，没有仔细检索，大致发现口碑还不错，但不仅经常无法使用，最后还直接停止服务，并且不退款。而此代理服务是由私人企业提供，故其稳定性相对可信。至于其隐私性至少优于多数个人服务提供者。免费的服务我也用过，稳定性确实堪忧。

我所使用的是 S 80 G 套餐。此外，如遇问题，务必联系客服，其态度认真必不让你失望而归。

考虑到局势紧张，不再公开代理服务的名称，但改文章名字有记录啊……

**Comment by zuston** [comment]
现在还能用吗
会被封吗

**Comment by SeventeenCui** [comment]
你好，能不能给个邀请码，谢谢

**Comment by heytxz** [comment]
可以用的，最近局势紧张，但就像矛与盾一样，是同步升级的，不要担心。

**Comment by heytxz** [comment]
你好啊，现在需要邀请码了么？自己去注册就行吧

**Comment by SeventeenCui** [comment]
你好，现在注册需要邀请码

**Comment by wangleeyom** [comment]
现在是不是更名为`MonoCloud `了？稳定性怎么样？正在考虑入手

**Comment by heytxz** [comment]
三年了都比较稳定，官方已经建议不要公开讨论…

**Comment by wangleeyom** [comment]
ok，我懂了😊

**Comment by VNeddy** [comment]
您好，
现在注册需要邀请码了，求老用户帮助，万分感谢！！！
1044287944@qq.com

**Comment by TakiGuan** [comment]
同请老用户帮忙提供一个邀请码
knight.guan@gmail.com

**Comment by heytxz** [comment]
你好，请等一等，我等他们客服回复

**Comment by shure22** [comment]
您好，
不知道您方便提供一个邀请码嘛？十分感谢！2807337801@qq.com

**Comment by pengwk** [comment]
您好，方便提供一个邀请码吗？不胜感激！pengwk@pengwk.com

**Comment by kennyhr** [comment]
最近自己的很多都不能用了，方便提供一个邀请码吗？十分感谢 kennyffly#gmail

**Comment by yxsongbo** [comment]
注册的时候提示This service is not available in your region

**Comment by yxsongbo** [comment]
可以指教下这么用吗？注册的时候提示你所在的地区没有提供服务
yxsongbo@qq.com

**Comment by heytxz** [comment]
暂时不会轻易提供邀请码，如果实在需要，[请在 Twitter 里私信我](https://twitter.com/heytxz)，并让我瞅瞅公开的推或微博之类的，滥发邀请码账号很有风险
