### ISSUE TITLE
为何 Shadowsocks 代理 Dropbox 无效及断网后无法恢复连接

### ISSUE THREAD

**Issue by heytxz** [heytxz/blog#56]
### 代理无效
在 首选项/网络/代理服务器 中设置，如果服务器设置为 127.0.0.1 1080 不起作用，那就设为 localhost 1080。
```
代理服务器设置：手动
代理服务器类型：socks5
服务器：localhost 1080 或者 127.0.0.1 1080
```
如果使用 ShadowSocksX-NG，端口由 1080 改为 1086，不是 10086...
 
### 离线后无法恢复连接
在使用 ShadowSocksX 代理 Dropbox 时断网后，又连网，而 Dropbox 却无法恢复连接。

解决方案
换用 ShadowSocksX-NG 不会再出现此问题。

**Comment by daizy008** [comment]
仍然不行。db设置页面还是无法打开

**Comment by heytxz** [comment]
设置页面打不开是软件的问题吧…… 这篇文章解决的是正常访问的问题
