### ISSUE TITLE
Apple Watch 堪为最佳伴侣

### ISSUE THREAD

**Issue by heytxz** [heytxz/blog#59]
此文最新版本在 [少数派](https://sspai.com/post/41832)

如果使用 Apple 设备，Apple Watch 的确堪为最佳伴侣，但也并非必需品，单身贵族一样可以过得好…… 但有个伴侣可能更好。

初入 Apple Watch 时，我想它会成为我的效率工具，这也是劝服自己花钱的最主要理由。为此我特意下载了 OmniFocus 以示决心，不出两周我渐渐明白其实所谓效率工具的确只是花钱的理由，而非内心对它真实的定位：一个好伙伴，即可以帮我实现一些事，让我能够做到更懒的程度。

![OmniFocus for Apple Watch](https://user-images.githubusercontent.com/9845703/32817105-0d40b7a0-c9f7-11e7-90a5-873decfe9172.png)

运动，Apple Watch 主要宣传的功能之一，也的确予人欣悦。开通一号多端业务后，AW 3 就成了 iPhone 分身，无需再携带手机，只需手腕处的 AW 跑步就不会再漏掉电话，也能以更舒适的方式检测运动状态，搭配 AirPods 听音乐也成了更赏心悦目的美事。单独的 Apple Watch 像是龙游浅水，接打电话、听音乐均外放的话，不仅太傻乎，也可能太耗电。对于 Apple 设备，AirPods 无愧于最具明天属性的无线蓝牙耳机。 

![running-faces](https://user-images.githubusercontent.com/9845703/32817923-5bae0a56-c9fb-11e7-8dc3-e9ccae30e5f4.png)

运动是主要的生活方式，但并不是最频繁的行动。比如，在繁忙时候我常需要在特定时间起床，现在终于有了 Apple Watch 默默叫醒我；之前借助 iPhone 三方应用解锁 Mac 的体验并不好，而 AW 可以无缝实现。 

_配图来自 https://birchtree.me/blog/apple-watch-early-review/_

**Comment by wangleeyom** [comment]
现在`Apple Watch 3`支持联通吗？貌似听说取消掉了？

**Comment by heytxz** [comment]
已经开通的不受影响，刚上市就买了，那会可以的
